name: Commando
on:
  workflow_dispatch:
    inputs:
      repos:
        required: true
        type: string
      branch:
        required: true
        type: string
      command:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      pr_title:
        required: true
        type: string
      pr_body:
        required: true
        type: string
jobs:
  commando:
    name: Commando
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3.10 -m pip install pipx
      - run: python3.10 -m pipx install tox
      - run: python3.10 -m pipx install "git+https://github.com/hypothesis/gh-pr-upsert.git@initial-implementation"
      - run: python3.10 -m pipx install "git+https://github.com/hypothesis/commando.git@initial-implementation"
      - run: commando --repos ${{ inputs.repos }} --branch "${{ inputs.branch }}" --command "${{ inputs.command }}" --commit-message "${{ inputs.commit_message }}" --pr-title "${{ inputs.pr_title }}" --pr-body "${{ inputs.pr_body }}"
        env:
          GH_TOKEN: ${{ github.token }}
