name: Commando
on:
  workflow_dispatch:
    inputs:
      repos:
        type: string
      branch:
        type: string
      command:
        type: string
      commit_message:
        type: string
      pr_title:
        type: string
      pr_body:
        type: string
jobs:
  commando:
    name: Commando
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pipx
      - run: pipx install "git+https://github.com/hypothesis/gh-pr-upsert.git@initial-implementation"
      - run: pipx install "git+https://github.com/hypothesis/commando.git@initial-implementation"
      - run: commando --help
